options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'ubuntu'
    id: 'List Files'
    entrypoint: 'bash'
    args: ['-c', 'ls -lR && echo "--- terraform/ ---" && ls -l infra-project/terraform']

  - name: 'hashicorp/terraform:1.6.6'
    id: 'Terraform Validate'
    dir: infra-project/terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform fmt -check -recursive
        terraform init
        terraform validate

  - name: 'hashicorp/terraform:1.6.6'
    id: 'Terraform Plan to JSON'
    dir: infra-project/terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform plan -out=tfplan
        terraform show -json tfplan > tfplan.json

  - name: 'openpolicyagent/conftest'
    id: 'Policy Scan'
    dir: infra-project/terraform
    args: ['test', 'tfplan.json', '--policy=../policies']

  - name: 'hashicorp/terraform:1.6.6'
    id: 'Terraform Apply'
    dir: infra-project/terraform
    args: ['apply', '-auto-approve', 'tfplan']

timeout: 1200s